test10/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^test100/', include('test100.urls', namespace = 'test100')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

test100/urls.py
from django.conf.urls import url
from . import views
import os
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about$', views.about, name='about'),
    url(r'^(?P<item_id>\d+)/$', views.detail, name='detail'),
    url(r'^suggestions$', views.suggestions, name='suggestions'),
    url(r'^newitem$', views.newitem, name='newitem'),
    url(r'^searchlib$',views.searchlib, name='searchlib'),
    url(r'^result$', views.result, name='result'),
    url(r'^login$', views.user_login, name='login'),
    url(r'^logout$', views.user_logout, name='logout'),
    url(r'^myitems$', views.myitems, name='myitems'),
    url(r'^register$', views.register, name='register'),
    url(r'^book$', views.book, name='book'),
    url(r'^dvd$', views.dvd, name='dvd'),
    url(r'^other$', views.other, name='other'),
    url(r'^suggestdetail/(?P<suggest_id>\d+$)', views.suggestdetail, name='suggestdetail')

        ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

test100/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
import django.utils
from PIL import Image


# Create your models here.

class Libuser(User):
    PROVINCE_CHOICES = (
        ('AB', 'Alberta'),  # The first value is actually stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    phone = models.IntegerField(null=True, blank=True)
    postalcode = models.CharField(max_length=6,null=True, blank=True)

    def __str__(self):
        return self.first_name


class Libitem(models.Model):
    TYPE_CHOICES = (
        ('Book', 'Book'),
        ('DVD', 'DVD'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=100)
    itemtype = models.CharField(max_length=6, choices=TYPE_CHOICES, default='Other')
    checked_out = models.BooleanField(default=False)
    user = models.ForeignKey(Libuser, default=None, null=True, blank=True)
    duedate = models.DateField(default=None, null=True, blank=True)
    last_chkout = models.DateField(default=None, null=True, blank=True)
    date_acquired = models.DateField(default=django.utils.timezone.now)
    pubyr = models.IntegerField()
    num_chkout = models.IntegerField(null=False, default=0)
    barcode = models.IntegerField(null=True)

    def __str__(self):
        return self.title

    def overdue(self):
        if self.checked_out == True :
            if self.duedate == None:
                return 'No'
            elif self.duedate < datetime.date.today():
                return  'Yes'
            else:
                return 'No'


class Book(Libitem):
    CATEGORY_CHOICES = (
        (1, 'Fiction'),
        (2, 'Biography'),
        (3, 'Self Help'),
        (4, 'Education'),
        (5, 'Children'),
        (6, 'Teen'),
        (7, 'Other'),
    )
    author = models.CharField(max_length=100)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)

    def __str__(self):
        return self.title + ' by ' + self.author


class DVD(Libitem):
    RATING_CHOICE = (
        (1, 'G'),
        (2, 'PG'),
        (3, 'PG-13'),
        (4, '14A'),
        (5, 'R'),
        (6, 'NR'),
    )
    maker = models.CharField(max_length=100)
    duration = models.IntegerField()
    rating = models.IntegerField(choices=RATING_CHOICE, default=1)

    def __str__(self):
        return self.title + ' by ' + self.maker


# database for suggested items
class Suggestion(models.Model):
    TYPE_CHOICES = (
        ('Book', 'Book'),
        ('DVD','DVD'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=100)
    pubyr = models.IntegerField(null=True, blank=True) #limited from 1900 to 2016
    type = models.CharField(max_length=6, default='Other', choices=TYPE_CHOICES)
    cost = models.IntegerField()
    num_interested = models.IntegerField(null=True, blank=True)
    comments = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

test100/forms.py
from django import forms
from test100.models import Suggestion, Libuser, User


# A form for users to make a suggestion; related to newitem view
class SuggestionForm(forms.ModelForm):
    cost=forms.IntegerField(label='Estimated Cost in Dollars')
    type=forms.ChoiceField(choices=Suggestion.TYPE_CHOICES , widget=forms.RadioSelect)
    pubyr= forms.IntegerField(min_value=1900,max_value=2016)
    class Meta:
        model = Suggestion
        fields=['title', 'pubyr', 'cost', 'comments', 'type']
form = SuggestionForm()


# A form for searching books and dvds; related to searchlib view
class SearchlibForm(forms.Form):
    title = forms.CharField(max_length=100, required=False)
    author = forms.CharField(max_length=100, required=False)# books only
    maker = forms.CharField(max_length=100, required=False)# dvds only
form = SearchlibForm()


# A form for new library user to register; related to register view
class RegisterForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    first_name=forms.CharField(max_length=100, required=False)
    last_name=forms.CharField(max_length=100, required=False)
    email = forms.CharField(max_length=100, required=False)

    class Meta:
        model = Libuser
        fields=['username', 'password', 'first_name', 'last_name', 'email']
form=RegisterForm()

test100/views.py
# Import necessary classes
from django.shortcuts import render
from django.http import HttpResponse
from test100.models import Book, DVD, Libuser, Libitem, Suggestion
from test100.forms import SuggestionForm, SearchlibForm, RegisterForm
from django.conf.urls import patterns, url
from django.http import Http404
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
import random
from PIL import Image
import barcode # barcode generrator! downdloaded from https://bitbucket.org/whitie/python-barcode/
from barcode.writer import ImageWriter # default barcode image generator
import shutil
import os



# Create your views here.


# Index page
def index(request):
    itemlist = Libitem.objects.all().order_by('title')[:10]
    return render(request, "test100/index.html", {'itemlist': itemlist})


# About page
def about(request):
    # counting how many times that about page has been visited by using cookies
    if 'about_visits' in request.COOKIES:
        aboutVisits = int(request.COOKIES['about_visits']) + 1
    else:
        aboutVisits = 1
    response = render(request, 'test100/about.html', {'aboutVisits': aboutVisits})
    response.set_cookie('about_visits', aboutVisits, 300)
    return response


# Detial page; showing detail information about books or dvds
def detail(request, item_id):
    # select targeted item and create its own barcode image when user clicks
    try:
        item = Libitem.objects.get(pk=item_id)
        code = str(item.barcode) # transfer integers into strings
        # targeted item is a book
        if item.itemtype == 'Book':
            items = Book.objects.get(pk=item_id)
            # generate barcode picture
            ean = barcode.get('ean8',code, writer=ImageWriter())
            # moving the picture to static/bar-img/books
            bar_name = item.title
            bar_pic = ean.save(bar_name)
            shutil.copy(bar_pic, 'test100/static/bar-img/book/')
            os.remove(bar_pic)
            # create url for detail page to display the barcode iamge
            bar_url = 'bar-img/book/' + bar_name + '.png'
        # targeted item is a dvd
        else:
            items = DVD.objects.get(pk=item_id)
            # generate barcode picture
            ean = barcode.get('ean8', code, writer=ImageWriter())
            # moving the picture to static/bar-img/books
            bar_name = item.title
            bar_pic = ean.save(bar_name)
            shutil.copy(bar_pic, 'test100/static/bar-img/dvd/')
            os.remove(bar_pic)
            # create url for detail page to display the barcode iamge
            bar_url = 'bar-img/dvd/' + bar_name + '.png'
        return render(request, 'test100/detail.html', {'item': items, 'bar_url':bar_url})
    except:
        raise Http404


# Suggestions page which shows all suggestions that made by the user
def suggestions(request):
    suggestionlist = Suggestion.objects.all()[:10]
    return render(request, 'test100/suggestions.html', {'itemlist': suggestionlist})


# Suggestiondetail page which shows detail information about selected item
def suggestdetail(request, suggest_id):
    try:
        suggestlist = Suggestion.objects.get(pk=suggest_id)
        return render(request, 'test100/suggestdetail.html', {'suggestlist': suggestlist})
    except:
        raise Http404


# Newitem page where an user can make a new suggestion
def newitem(request):
    suggestions = Suggestion.objects.all()
    if request.method == 'POST':
        form = SuggestionForm(request.POST) # check forms.py: SuggestionForm
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.num_interested = 1
            suggestion.save()
            return HttpResponseRedirect(reverse('test100:suggestions'))
        else:
            return render(request, 'test100/newitem.html', {'form': form, 'suggestions': suggestions})
    else:
        form = SuggestionForm()
        return render(request, 'test100/newitem.html', {'form': form, 'suggestions': suggestions})


# Searchlib page; users search for books or dvds
def searchlib(request):
    if request.method == 'GET':
        form = SearchlibForm() # check forms.py: SearchlibForm
        return render(request, 'test100/searchlib.html')
    else:
        return HttpResponseRedirect(reverse('test100:searchlib'))


# Result page; showing the result that searched by user
def result(request):
    # get information from keyboard typing
    if 'title'or 'author' or 'maker' in request.GET:
        title = request.GET['title']
        author = request.GET['author']
        maker = request.GET['maker']
        # rules: a book has title and author, a dvd has title and maker, user can search either or both
        try:
            # an item cannot have both author and maker
            if author and maker:
                message = 'Wow! Please fill in either author or maker '
                return render(request, 'test100/result.html', {'message':message})
            # search title - including books and dvds
            elif title:
                items = DVD.objects.filter(title__icontains=title) or Book.objects.filter(title__icontains=title)
            # search a dvd
            elif title and maker:
                items = DVD.objects.filter(title__icontains=title).filter(maker__icontains=maker)
            elif maker:
                items = DVD.objects.filter(maker__icontains=maker)
            # search a book
            elif title and author:
                items = Book.objects.filter(title__icontains=title).filter(author__icontains=author)
            elif author:
                items = Book.objects.filter(author__icontains=author)
            return render(request, 'test100/result.html', {'items':items, 'title':title, 'author':author, 'maker':maker})
        except:
            message = 'You submitted an empty form' # when user did not type anything and submit an empty form
        return render(request, 'test100/result.html', {'message':message})


# Login page
def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        request.session.set_expiry(3600)
        # user status check
        if user:
            if user.is_active:
                # get or set luckynum
                if 'luckynum' in request.session:
                    luckynum = request.session.get('luckynum')
                else:
                    request.session['luckynum'] = str(random.randint(1,9))
                login(request, user)
                return HttpResponseRedirect(reverse('test100:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'test100/login.html')


# User logout and return to index
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('test100:index')))


# Myitem page; shows all items that a user borrows, staff and superusers cannot borrow items form library
def myitems(request):
    # check if the user is a library user
    if request.user.is_authenticated():
        try:
            Libuser.objects.get(username=request.user)
        except:
            message = 'You are not a Libuser'
            return render(request, 'test100/myitems.html', {'message':message})
        # show all items borrowed by specific user
        myitem=Libitem.objects.filter(checked_out=True).filter(user=request.user)
        return render(request, 'test100/myitems.html', {'myitem':myitem})
    else:
        message = 'login please'
        return render(request, 'test100/myitems.html', {'message':message})


# Register page; a student can register as a library user here
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST) # check forms.py: RegisterForm
        if form.is_valid():
            username=request.POST['username']
            email=request.POST['email']
            password=request.POST['password']
            firstname=request.POST['first_name']
            lastname=request.POST['last_name']
            user = Libuser.objects.create_user(username, email, password)
            user.last_name=lastname
            user.first_name=firstname
            user.save()
            return HttpResponseRedirect(reverse( 'test100:index'))
        else:
            return render(request, 'test100/register.html', {'form':form})
    else:
        form = RegisterForm()
        return render(request, 'test100/register.html', {'form':form})


# Book page; show all books
def book(request):
    booklist=Book.objects.all()
    return render(request, 'test100/book.html', {'booklist':booklist})


# Dvd page; show all dvds
def dvd(request):
    dvdlist=DVD.objects.all()
    return render(request, 'test100/dvd.html', {'dvdlist':dvdlist})


# Other page; show all other items
def other(request):
    otherlist=Libitem.objects.filter(itemtype='Other')
    return render(request, 'test100/other.html', {'otherlist':otherlist})

templates/test100/base.html
<!DOCTYPE html>

{% load staticfiles %}
{#{% load bootstrap3 %}#}

<head>
<title>MAC Library APP - {% block title %}Welcome!{% endblock %}</title>

        <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href={% static "Content/bootstrap.min.css"%}  />
        <link  rel="stylesheet" type="text/css" href={% static "libapp/style.css"%}  />
        <script src={% static "Scripts/jquery-1.9.1.min.js"%}></script>
        <script src={% static "Scripts/bootstrap.min.js"%}></script>
        <link  rel="stylesheet" type="text/css" href={% static "Content/animate.css"%}  />
        <script src={% static "Scripts/wow.min.js"%}></script>
</head>


<html lang="en" xmlns="http://www.w3.org/1999/html">
<body>
    <header class="container-fluid">

<img class="img-responsive" src="{% static 'images/banner2.png' %}" alt="library"/>
    </header>



{#----------------------------------------------------------------------------------------------------------------#}
    <nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
{#             <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>#}
          <li> <a href = "{% url 'test100:index' %}">Home</a></li>
          <li><a href="{% url 'test100:about' %}">About</a></li>
          <li><a href="{% url 'test100:searchlib' %}">Search Books</a></li>
          <li><a href="{% url 'test100:suggestions' %}">View Suggestions</a></li>
          <li><a href="{% url 'test100:newitem' %}">Suggest Items</a></li>
          {% if request.user.is_authenticated%}
          <li><a href = "{% url 'test100:logout' %}"> logout</a></li>
          <li> <a href = "{% url 'test100:myitems' %}">My Account</a></li>
          {% else %}
          <li> <a href = "{% url 'test100:login' %}"> login</a></li>
          <li> <a href = "{% url 'test100:register' %}">Register</a></li>
          {% endif %}
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>
{#-------------------------------------------------------------------------------------------------------------#}


        <div class="content">
            <h1>{% block myhdg %}Hello {{ user.first_name }}{% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <footer class="container-fluid">  Created by Mac program 60-634-52 Group3 </footer>



</body>
</html>

templates/test100/book.html
{% extends 'test100/base.html' %}
{% block body_block %}
    <h2>List of Library Books</h2>
{% if booklist %}
    <ol>
    {% for book in booklist %}
    <li><a href="/test100/{{ book.id }}"> {{ book }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <strong>There is no book in library!</strong>
{% endif %}


{% endblock %}

templates/test100/detail.html
{% extends 'test100/base.html' %}
{% load staticfiles %}
{% block body_block %}
    {% if item.itemtype == 'Book' %}
        <h3>This is Book item</h3>
            Title: {{ item.title }}<br/>
            Published Year: {{ item.pubyr }}<br/>
            Author: {{ item.author }}<br/>
            Category: {{ item.get_category_display }}<br>
{#        {{ item.barcode }}<br/>#}

    {%  else %}
    <h3>This is DVD item</h3>
            Title: {{ item.title }}<br/>
            Published Year: {{ item.pubyr}}<br/>
            Maker: {{ item.maker }}<br/>
            Duration: {{ item.duration }}<br/>
            Rating:{{ item.get_rating_display }}<br/>

    {% endif %}
    <img height="90px" width="160px" src={% static bar_url %} , alt="ean8" />
{% endblock %}

templates/test100/dvd.html
{% extends 'test100/base.html' %}
{% block body_block %}
    <h2>List of Library DVDs</h2>
{% if dvdlist %}
    <ol>
    {% for dvd in dvdlist %}
    <li><a href="/test100/{{ dvd.id }}"> {{ dvd }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <strong>There is no DVD in library!</strong>
{% endif %}


{% endblock %}

templates/test100/index.html
{% extends 'test100/base.html' %}
{% block body_block %}

{% include 'test100/index_old.html' %}

{% endblock %}

templates/test100/index_old.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
    <script>
        //initialize WOW for element animation
        new WOW().init()
    </script>

<head lang="en">
    <meta charset="UTF-8">
    <title>My Library APP</title>
</head>

<body>
<hr>
            <section id="activities" class="row activity-section">

                <div class="activity-element col-md-4 wow flip">
		            <a href ={% url 'test100:book' %} style="outline:none"> <img src={% static "images/books-icon.png" %} alt="book">
                        <p>Books</p>
                    </a>
                </div>
                <div class="activity-element col-md-4 wow flip">
		            <a href ={% url 'test100:dvd' %} style="outline:none"> <img src={% static "images/dvd-icon.png" %} alt="dvd">
                        <p> DVDs </p>
		            </a>
                </div>
                <div class="activity-element col-md-4 wow flip">
                    <a href ={% url 'test100:other' %} style="outline:none"> <img src={% static "images/item-icon.png" %} alt="item">
                        <p>Other Items</p>
                    </a>
                </div>
            </section>
    </div>
    <hr>
    {# user's lucky number #}
    {% ifnotequal request.session.luckynum None %}
        <h4>Lucky Number: {{ request.session.luckynum }}</h4>
    {% else %}
        <h4>Lucky Number: 0</h4>
    {% endifnotequal %}
</body>
</html>

templates/test100/login.html
{% extends 'test100/base.html' %}
{% block body_block %}
<h1>User Login</h1>
<form action="" method="post"> {# a form for user login #}
    {% csrf_token %}
    <label for="username">User name:</label>
    <input type="text" name="username" value="" id="username">
    <label for="password">Password:</label>
    <input type="password" name="password" value="" id="password">

    <input type="submit" value="login" />
  </form>
{% endblock %}

templates/test100/myitems.html
{% extends 'test100/base.html' %}
{% block body_block %}
    {% if message %} {# check if there is any error occurs first #}
        {{ message }} {# show error information  #}
{% elif myitem  %}
    <h2>Items checked out by {{ user.first_name }}</h2>
    <ol>
        {% for item in myitem %}
            <li>{{ item.get_itemtype_display}}:  {{ item }}</li> {# format: itemtype:title  #}
        {% endfor %}
    </ol>

{% else %} {# when the user does not borrow any item from libray #}
    <strong>There is no available items!</strong>
{% endif %}

{% endblock %}

templates/test100/newitem.html
{% extends 'test100/base.html' %}
{% block body_block %}
<form action="/test100/newitem" method="post"> {# transfer SuggestionForm #}
    {% csrf_token %}
    {{ form.as_p }} {# show as paragraph #}
    <input type="submit" value="Submit" />
</form>


{% endblock %}

templates/test100/register.html
{% extends 'test100/base.html' %}
{% block body_block %}
<form action="" method="post"> {# transfer RegisterForm #}
    {% csrf_token %}
    {{ form.as_p }} {# show as paragraph #}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

templates/test100/result.html
{% extends 'test100/base.html' %}
{% block body_block %}
    {% if message %} {# check if any error message sent by result view first #}
        {{ message }} {# show error message if one appears #}
    {% else %} {# show search information #}
        <p>Your searched for title: '{{ title }}'</p>
        <p>Your searched books writtern by author: '{{ author }}'</p>
        <p>Your searched DVDs published by maker: '{{ maker }}'</p>
        <p>Search Result</p>
        {% for item in items %} {#  show results #}
             <p>{{ item.itemtype }}:{{ item.title }}    {{ item.maker }}{{ item.author }}</p>
        {% endfor %}
    {% endif %}
{% endblock %}

templates/test100/searchlib.html
{% extends 'test100/base.html' %}
{% block body_block %}
<h1>Search in Library</h1>
<form action="/test100/result" method="get">
   Title Search:<input type="text" name="title"> {# key words for a book or a dvd title #}
   Author Search:<input type="text" name="author">  {# key words for a book author #}
    Maker Search:<input type="text" name="maker"> {# key words for a dvd maker #}
   <p><input type="submit" value="Search"></p>
</form>
{% endblock %}

templates/test100/suggestdetail.html
{% extends 'test100/base.html' %}
{% block body_block %}
    {% if suggestlist %}
        Title: {{ suggestlist.title }}<br/>
        Type: {{ suggestlist.get_type_display }}<br/>
        Publish Year: {{ suggestlist.pubyr }}<br/>
        Cost: {{ suggestlist.cost }}<br/>
        Comments: {{ suggestlist.comments }}<br/>
    {% else %}
        No such item in Suggestion list.
    {% endif %}
{% endblock %}

templates/test100/suggestions.html
{% extends 'test100/base.html' %} {#base background#}
{% block body_block %}
{% if itemlist %} {# get list form  suggestions view #}
    <h2>List of Suggestion items for purchasing</h2>
    <ol>
        {% for item in itemlist %}
            <li><a href="/test100/suggestdetail/{{ item.id}}">{{ item.get_type_display}}:  {{ item}} </a></li> {# create links for detail information and redirect to suggestdetial page  #}
        {% endfor %}
    </ol>

{% else %}
    <strong>There are no available items!</strong> {# no suggestion item was found #}
{% endif %}

{% endblock %}